### ISSUE TITLE
inference with checkpoint

### ISSUE THREAD

**Issue by eschmidbauer** [ighodgao/mamba-speech-synthesis#1]
Hi! 
Thank you for sharing this work - I am very interested in SSM + TTS
i followed your steps to train a model based on a small datasets. I uploaded the checkpoint here
https://huggingface.co/eschmidbauer/mamba-speech-synthesis
is there anyway to perform TTS with text input instead of tokens from a waveform?

**Comment by ighodgao** [comment]
Hello! Thanks for trying it out! 

The unconditional generation function starts with a token vector - maybe you could try using a [text tokenizer](https://platform.openai.com/tokenizer) of some kind and then pass that into one of the generation functions? I haven't tried this myself, but if you do try it, let me know how it works out!

**Comment by eschmidbauer** [comment]
i was able to leverage some code from WhisperSpeech to generate TTS
```python
from whisperspeech.pipeline import Pipeline
tts_pipe = Pipeline(t2s_ref="collabora/whisperspeech:t2s-tiny-en+pl.model", s2a_ref="collabora/whisperspeech:s2a-q4-tiny-en+pl.model", torch_compile=True, device="cuda")  # noqa
p = tts_pipe.generate_atoks(text="U.S. stocks are poised for slight bounce back after worst day in almost 2 years", step_callback=None)  # noqa
wav_t = tts_pipe.vocoder.decode(p)  # noqa
waveform = normalize_waveform(wav_t, 24000)
tokens = tokenize(waveform)
k = tokens[0]
produce_wav('test1', model, k)
```

This may not be efficient as whisperspeech is generating the waveform and then mamba tokenizes waveform to generate audio but the output speech sounds pretty good considering

**Comment by ighodgao** [comment]
Awesome! Feel free to create a pull request
